# Site settings
title: Matt: Orange, Blue, Grey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Coding, Board & Video Games, Food, Film, Classical Music. All things Matt.

  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Mattbrosenberg
github_username:  Mattbrosenberg

# Build settings
markdown: kramdown
