title: Matt
email: matthew.b.rosenberg@gmail.comi
description:
  Coding, Board & Video Games, Food, Film, Classical Music. All things Matt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Mattbrosenberg
github_username:  Mattbrosenberg

# Build settings
markdown: kramdown
